{% set name = "unzip-http" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unzip-http-{{ version }}.tar.gz
  sha256: 7c24c6f1d79e957b3ea3b8619d02c15a6233f76a7c73588282c914571b70f6c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - urllib3

test:
  imports:
    - unzip_http
  commands:
    - unzip-http
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saulpw/unzip-http
  summary: extract files from .zip files over http without downloading entire archive
  license: MIT
  license_file: LICENSE-mit.txt

extra:
  recipe-maintainers:
    - gforsyth
    - anjakefala
