{% set name = "unzip-http" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 937996fe7c8fa9c43c2464f7d99ed31dce1aed168b77e5b6633ab962ffd23d77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - urllib3

test:
  imports:
    - unzip_http
  commands:
    - unzip-http
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saulpw/unzip-http
  summary: extract files from .zip files over http without downloading entire archive
  license: MIT
  license_file: LICENSE-mit.txt

extra:
  recipe-maintainers:
    - gforsyth
    - anjakefala
