{% set name = "unzip-http" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unzip-http-{{ version }}.tar.gz
  sha256: 4b9dc5bea5e38164fe45110115b10f287440edde8ecb4be661d1c612feb2b2c8

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - urllib3

test:
  imports:
    - unzip_http
  commands:
    - unzip-http -h
  requires:
    - pip

about:
  home: https://github.com/saulpw/unzip-http
  summary: extract files from .zip files over http without downloading entire archive
  license: MIT
  license_file: LICENSE-mit.txt

extra:
  recipe-maintainers:
    - gforsyth
    - anjakefala
